version: '2'

services:

  consul:
    image: consul:latest
    
  frontend:
    image: scipionyx/butterfly-effect-frontend:latest
    links: 
      - consul
    
  backend:
    image: scipionyx/butterfly-effect-backend:latest
    links: 
      - consul